server: 
  address: 
  port: 8081

spring: 
  datasource: 
    type: 
    url: jdbc:mysql://localhost:3306/activiti-demo2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  jpa: 
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate: 
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  activiti: 
    check-process-definitions: false

